// <auto-generated />
using System;
using Irt.Infrastructure.Database.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Irt.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250315142909_addipadresscol")]
    partial class addipadresscol
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Irt.Core.Datasets.Dataset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Bindings")
                        .HasColumnType("text");

                    b.Property<string>("CronExpression")
                        .HasColumnType("text");

                    b.Property<int>("DatasetType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelatedIndicatorsIds")
                        .HasColumnType("text");

                    b.Property<string>("Schedule")
                        .HasColumnType("text");

                    b.Property<string>("SpreadJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("datasets", "irt");
                });

            modelBuilder.Entity("Irt.Core.Datasources.Datasource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("DatasourceType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("datasources", "irt");
                });

            modelBuilder.Entity("Irt.Core.Datasets.Dataset", b =>
                {
                    b.OwnsOne("Irt.Core.ValueObjects.CreatedBy", "CreatedBy", b1 =>
                        {
                            b1.Property<string>("DatasetId")
                                .HasColumnType("text");

                            b1.HasKey("DatasetId");

                            b1.ToTable("datasets", "irt");

                            b1.WithOwner()
                                .HasForeignKey("DatasetId");
                        });

                    b.OwnsOne("Irt.Core.ValueObjects.LastModifiedBy", "LastModifiedBy", b1 =>
                        {
                            b1.Property<string>("DatasetId")
                                .HasColumnType("text");

                            b1.HasKey("DatasetId");

                            b1.ToTable("datasets", "irt");

                            b1.WithOwner()
                                .HasForeignKey("DatasetId");
                        });

                    b.Navigation("CreatedBy")
                        .IsRequired();

                    b.Navigation("LastModifiedBy")
                        .IsRequired();
                });

            modelBuilder.Entity("Irt.Core.Datasources.Datasource", b =>
                {
                    b.OwnsOne("Irt.Core.ValueObjects.CreatedBy", "CreatedBy", b1 =>
                        {
                            b1.Property<string>("DatasourceId")
                                .HasColumnType("text");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_ip");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_id");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_name");

                            b1.HasKey("DatasourceId");

                            b1.ToTable("datasources", "irt");

                            b1.WithOwner()
                                .HasForeignKey("DatasourceId");
                        });

                    b.OwnsOne("Irt.Core.ValueObjects.LastModifiedBy", "LastModifiedBy", b1 =>
                        {
                            b1.Property<string>("DatasourceId")
                                .HasColumnType("text");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_ip");

                            b1.Property<DateTime>("ModifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_id");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_name");

                            b1.HasKey("DatasourceId");

                            b1.ToTable("datasources", "irt");

                            b1.WithOwner()
                                .HasForeignKey("DatasourceId");
                        });

                    b.Navigation("CreatedBy")
                        .IsRequired();

                    b.Navigation("LastModifiedBy")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
