// <auto-generated />
using System;
using Irt.Infrastructure.Database.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Irt.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Irt.Core.Datasets.Dataset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Bindings")
                        .HasColumnType("text");

                    b.Property<string>("CronExpression")
                        .HasColumnType("text");

                    b.Property<int>("DatasetType")
                        .HasColumnType("integer");

                    b.Property<string>("DatasourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IndicatorDefinitionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelatedIndicatorsIds")
                        .HasColumnType("text");

                    b.Property<string>("Schedule")
                        .HasColumnType("text");

                    b.Property<string>("SpreadJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DatasourceId");

                    b.HasIndex("IndicatorDefinitionId");

                    b.ToTable("datasets", "irt");
                });

            modelBuilder.Entity("Irt.Core.Datasources.Datasource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("DatasourceType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("datasources", "irt");
                });

            modelBuilder.Entity("Irt.Core.IndicatorCategories.IndicatorCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IndicatorMainCategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IndicatorMainCategoryId");

                    b.ToTable("indicator_categories", "irt");
                });

            modelBuilder.Entity("Irt.Core.IndicatorDefinitions.IndicatorDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("indicator_definition_name");

                    b.Property<string>("DPSIR")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Formula")
                        .HasColumnType("text");

                    b.Property<string>("FormulaDescription")
                        .HasColumnType("text");

                    b.Property<string>("IndicatorCategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaxThreshold")
                        .HasColumnType("numeric");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<decimal>("MinThreshold")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportingScopeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitOfMeasureId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IndicatorCategoryId");

                    b.HasIndex("ReportingScopeId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("indicator_definitions", "irt");
                });

            modelBuilder.Entity("Irt.Core.IndicatorMainCategories.IndicatorMainCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("indicator_main_categories", "irt");
                });

            modelBuilder.Entity("Irt.Core.ReportingScopes.ReportingScope", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("reporting_scopes", "irt");
                });

            modelBuilder.Entity("Irt.Core.UnitOfMeasurements.UnitOfMeasure", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("unit_of_measures", "irt");
                });

            modelBuilder.Entity("Irt.Core.Datasets.Dataset", b =>
                {
                    b.HasOne("Irt.Core.Datasources.Datasource", "Datasource")
                        .WithMany()
                        .HasForeignKey("DatasourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Irt.Core.IndicatorDefinitions.IndicatorDefinition", "IndicatorDefinition")
                        .WithMany()
                        .HasForeignKey("IndicatorDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Irt.Core.ValueObjects.CreatedBy", "CreatedBy", b1 =>
                        {
                            b1.Property<string>("DatasetId")
                                .HasColumnType("text");

                            b1.Property<string>("Application")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_app");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_ip");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_id");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_name");

                            b1.HasKey("DatasetId");

                            b1.ToTable("datasets", "irt");

                            b1.WithOwner()
                                .HasForeignKey("DatasetId");
                        });

                    b.OwnsOne("Irt.Core.ValueObjects.LastModifiedBy", "LastModifiedBy", b1 =>
                        {
                            b1.Property<string>("DatasetId")
                                .HasColumnType("text");

                            b1.Property<string>("Application")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_app");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_ip");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_id");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_name");

                            b1.HasKey("DatasetId");

                            b1.ToTable("datasets", "irt");

                            b1.WithOwner()
                                .HasForeignKey("DatasetId");
                        });

                    b.Navigation("CreatedBy")
                        .IsRequired();

                    b.Navigation("Datasource");

                    b.Navigation("IndicatorDefinition");

                    b.Navigation("LastModifiedBy")
                        .IsRequired();
                });

            modelBuilder.Entity("Irt.Core.Datasources.Datasource", b =>
                {
                    b.OwnsOne("Irt.Core.ValueObjects.CreatedBy", "CreatedBy", b1 =>
                        {
                            b1.Property<string>("DatasourceId")
                                .HasColumnType("text");

                            b1.Property<string>("Application")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_app");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_ip");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_id");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_name");

                            b1.HasKey("DatasourceId");

                            b1.ToTable("datasources", "irt");

                            b1.WithOwner()
                                .HasForeignKey("DatasourceId");
                        });

                    b.OwnsOne("Irt.Core.ValueObjects.LastModifiedBy", "LastModifiedBy", b1 =>
                        {
                            b1.Property<string>("DatasourceId")
                                .HasColumnType("text");

                            b1.Property<string>("Application")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_app");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_ip");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_id");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_name");

                            b1.HasKey("DatasourceId");

                            b1.ToTable("datasources", "irt");

                            b1.WithOwner()
                                .HasForeignKey("DatasourceId");
                        });

                    b.Navigation("CreatedBy")
                        .IsRequired();

                    b.Navigation("LastModifiedBy")
                        .IsRequired();
                });

            modelBuilder.Entity("Irt.Core.IndicatorCategories.IndicatorCategory", b =>
                {
                    b.HasOne("Irt.Core.IndicatorMainCategories.IndicatorMainCategory", "IndicatorMainCategory")
                        .WithMany()
                        .HasForeignKey("IndicatorMainCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Irt.Core.ValueObjects.CreatedBy", "CreatedBy", b1 =>
                        {
                            b1.Property<string>("IndicatorCategoryId")
                                .HasColumnType("text");

                            b1.Property<string>("Application")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_app");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_ip");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_id");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_name");

                            b1.HasKey("IndicatorCategoryId");

                            b1.ToTable("indicator_categories", "irt");

                            b1.WithOwner()
                                .HasForeignKey("IndicatorCategoryId");
                        });

                    b.OwnsOne("Irt.Core.ValueObjects.LastModifiedBy", "LastModifiedBy", b1 =>
                        {
                            b1.Property<string>("IndicatorCategoryId")
                                .HasColumnType("text");

                            b1.Property<string>("Application")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_app");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_ip");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_id");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_name");

                            b1.HasKey("IndicatorCategoryId");

                            b1.ToTable("indicator_categories", "irt");

                            b1.WithOwner()
                                .HasForeignKey("IndicatorCategoryId");
                        });

                    b.Navigation("CreatedBy")
                        .IsRequired();

                    b.Navigation("IndicatorMainCategory");

                    b.Navigation("LastModifiedBy")
                        .IsRequired();
                });

            modelBuilder.Entity("Irt.Core.IndicatorDefinitions.IndicatorDefinition", b =>
                {
                    b.HasOne("Irt.Core.IndicatorCategories.IndicatorCategory", "IndicatorCategory")
                        .WithMany()
                        .HasForeignKey("IndicatorCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Irt.Core.ReportingScopes.ReportingScope", "ReportingScope")
                        .WithMany()
                        .HasForeignKey("ReportingScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Irt.Core.UnitOfMeasurements.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Irt.Core.ValueObjects.CreatedBy", "CreatedBy", b1 =>
                        {
                            b1.Property<string>("IndicatorDefinitionId")
                                .HasColumnType("text");

                            b1.Property<string>("Application")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_app");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_ip");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_id");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_name");

                            b1.HasKey("IndicatorDefinitionId");

                            b1.ToTable("indicator_definitions", "irt");

                            b1.WithOwner()
                                .HasForeignKey("IndicatorDefinitionId");
                        });

                    b.OwnsOne("Irt.Core.ValueObjects.LastModifiedBy", "LastModifiedBy", b1 =>
                        {
                            b1.Property<string>("IndicatorDefinitionId")
                                .HasColumnType("text");

                            b1.Property<string>("Application")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_app");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_ip");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_id");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_name");

                            b1.HasKey("IndicatorDefinitionId");

                            b1.ToTable("indicator_definitions", "irt");

                            b1.WithOwner()
                                .HasForeignKey("IndicatorDefinitionId");
                        });

                    b.Navigation("CreatedBy")
                        .IsRequired();

                    b.Navigation("IndicatorCategory");

                    b.Navigation("LastModifiedBy")
                        .IsRequired();

                    b.Navigation("ReportingScope");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("Irt.Core.IndicatorMainCategories.IndicatorMainCategory", b =>
                {
                    b.OwnsOne("Irt.Core.ValueObjects.CreatedBy", "CreatedBy", b1 =>
                        {
                            b1.Property<string>("IndicatorMainCategoryId")
                                .HasColumnType("text");

                            b1.Property<string>("Application")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_app");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_ip");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_id");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_name");

                            b1.HasKey("IndicatorMainCategoryId");

                            b1.ToTable("indicator_main_categories", "irt");

                            b1.WithOwner()
                                .HasForeignKey("IndicatorMainCategoryId");
                        });

                    b.OwnsOne("Irt.Core.ValueObjects.LastModifiedBy", "LastModifiedBy", b1 =>
                        {
                            b1.Property<string>("IndicatorMainCategoryId")
                                .HasColumnType("text");

                            b1.Property<string>("Application")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_app");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_ip");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_id");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_name");

                            b1.HasKey("IndicatorMainCategoryId");

                            b1.ToTable("indicator_main_categories", "irt");

                            b1.WithOwner()
                                .HasForeignKey("IndicatorMainCategoryId");
                        });

                    b.Navigation("CreatedBy")
                        .IsRequired();

                    b.Navigation("LastModifiedBy")
                        .IsRequired();
                });

            modelBuilder.Entity("Irt.Core.ReportingScopes.ReportingScope", b =>
                {
                    b.OwnsOne("Irt.Core.ValueObjects.CreatedBy", "CreatedBy", b1 =>
                        {
                            b1.Property<string>("ReportingScopeId")
                                .HasColumnType("text");

                            b1.Property<string>("Application")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_app");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_ip");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_id");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_name");

                            b1.HasKey("ReportingScopeId");

                            b1.ToTable("reporting_scopes", "irt");

                            b1.WithOwner()
                                .HasForeignKey("ReportingScopeId");
                        });

                    b.OwnsOne("Irt.Core.ValueObjects.LastModifiedBy", "LastModifiedBy", b1 =>
                        {
                            b1.Property<string>("ReportingScopeId")
                                .HasColumnType("text");

                            b1.Property<string>("Application")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_app");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_ip");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_id");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_name");

                            b1.HasKey("ReportingScopeId");

                            b1.ToTable("reporting_scopes", "irt");

                            b1.WithOwner()
                                .HasForeignKey("ReportingScopeId");
                        });

                    b.Navigation("CreatedBy")
                        .IsRequired();

                    b.Navigation("LastModifiedBy")
                        .IsRequired();
                });

            modelBuilder.Entity("Irt.Core.UnitOfMeasurements.UnitOfMeasure", b =>
                {
                    b.OwnsOne("Irt.Core.ValueObjects.CreatedBy", "CreatedBy", b1 =>
                        {
                            b1.Property<string>("UnitOfMeasureId")
                                .HasColumnType("text");

                            b1.Property<string>("Application")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_app");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_ip");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_id");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by_name");

                            b1.HasKey("UnitOfMeasureId");

                            b1.ToTable("unit_of_measures", "irt");

                            b1.WithOwner()
                                .HasForeignKey("UnitOfMeasureId");
                        });

                    b.OwnsOne("Irt.Core.ValueObjects.LastModifiedBy", "LastModifiedBy", b1 =>
                        {
                            b1.Property<string>("UnitOfMeasureId")
                                .HasColumnType("text");

                            b1.Property<string>("Application")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_app");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_ip");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_id");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_modified_by_name");

                            b1.HasKey("UnitOfMeasureId");

                            b1.ToTable("unit_of_measures", "irt");

                            b1.WithOwner()
                                .HasForeignKey("UnitOfMeasureId");
                        });

                    b.Navigation("CreatedBy")
                        .IsRequired();

                    b.Navigation("LastModifiedBy")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
